### ISSUE TITLE
Only display shifts that users have access to

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/thadmin#15]
Not implemented in concrexit yet and also more of an issue for that PR, but we should have shift-specific permissions.
For example, during a borrel, only the borrelcie should be allowed to use the thadmin (and perhaps the board), while during certain other events, only those committees should be.
And regular members that aren't even committee members shouldn't be able to manage any shifts (I don't have problems with them login in, but it should just display no shifts).

On the shifts page, we should only display shifts we have access to

**Comment by JobDoesburg** [comment]
We could completely implement this on the concrexit-side by not even returning those shifts in the API. Im probably in favor of that

**Comment by se-bastiaan** [comment]
This should definitely be implemented in the API

**Comment by JobDoesburg** [comment]
Yeah of course, but I was in doubt whether users should be allowed to read shifts they don't have access to. But I already figured the answer to that answer is no
