### ISSUE TITLE
Do not always request deployment

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/thadmin#23]
Right now, on every push and every change to master, a deploy to development is requested. This generates a lot of email traffic to me, which is undesirable. In my opinion, deployments (even to development) should be manual actions. 

My suggestion would be to have the 'request deployment to development' be a workflow that must be triggered manually. Then, we should have a branch protection rule on master, requiring review from svthalia/technicie and requiring a successful deploy to development. The deploy to staging can then happen automatically (because the master branch is protected already).

A deploy to production should then only be triggered upon creating a release and should request deployment approval by svthalia/technicie/illuminati.

**Comment by se-bastiaan** [comment]
I have not yet checked my email, but the notifications area in GitHub was pretty crowded.

I am not sure if we need to require a successful deployment in a PR. I mainly added it to make it easy to check the changes without pulling locally. Although, we have unlimited actions so there is no real reason that really blocks it.

**Comment by se-bastiaan** [comment]
I think I solved this, but there is no way to force a deployment before merging because it does not use the branch

**Comment by se-bastiaan** [comment]
<img width="982" alt="Screenshot 2021-05-05 at 14 26 41" src="https://user-images.githubusercontent.com/1799914/117140654-f10c6180-adad-11eb-8d17-f67aae450bf4.png">
 
Fixed
