### ISSUE TITLE
Add Sentry error reporting

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/thadmin#9]
### Is your feature request related to a problem? Please describe.
It can happen that we need to know why the app is crashing for a lot of users.

### Describe the solution you'd like
We should implement error reporting to Sentry to make sure we are properly informed about the stability of the app.

### Motivation
I think I have already motivated this feature.

### Describe alternatives you've considered
There are no alternative services since we have a open source account for Sentry and concrexit already uses it as well.

**Comment by Luca-Castelnuovo** [comment]
https://sentry.io/thalia/thadmin/getting-started/javascript-vue/

**Comment by Luca-Castelnuovo** [comment]
Code is done, will commit tomorrow

**Comment by Luca-Castelnuovo** [comment]
Note: AdBlockers can block sentry script
